name: 'Label Regex'
description: 'Use Pull Request fields and regex to create and assign automatically label on Pull Requests'
branding:
  icon: tag
  color: yellow
inputs:
  field:
    description: 'The field to apply the regex and found the label. Permitted values or `title`, `branch` and `body`.'
    required: true
    default: 'World'
  regex:
    description: 'The regex to match with the field. Example: `([A-Z]+)-`, will match `FIX-1234 My awsome bug fix` => `FIX`'
    required: true
    default: 'World'
  lowercase:
    description: 'Force to lowercase the label to assign'
    required: false
    default: true
  token:
    description: 'A personal Github access token'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
